### PR TITLE
Add capability to handle unknown subs at runtime

### PR DESCRIPTION
**Pull request by dylanjm**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

Refs idaholab/HERON#38 and #1335 

##### What are the significant changes in functionality due to this change request?

By adding an `unknownSubs` boolean value to the utils::InputParameter class we
can handle InputParameter classes that may have an unknown name or number of
variables.

This is handled by checking the `unknownSubs` boolean during parsing. If `True`
it will add the sub to the class on the fly.

This only applies to subparts on input parameters and will default to using
`InputTypes.InputString` as its' type.

See the referenced issue for a use-case. This could be helpful for users who
want to feed-forward static data through the RAVEN stack.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
How does this interact with the automatic documentation generation?

Also, there may be overlap between `strict=False` and `unknownSubs=True`. @joshua-cogliati-inl @alfoa if we have strict mode on False for an InputData node, that implies accepting anything under it but doesn't actually read them into the specs, right? Could we use Dylan's fix based on the strict mode instead of with another flag, or does strict mode do something else too?

**Comment by dylanjm** [comment]
> How does this interact with the automatic documentation generation? 

@PaulTalbot-INL I was thinking the same thing. Since these nodes would be unknown there would be no way to officially document them. What's nice is that you can still add documented subnodes to the class, it should be mentioned in the documentation that unknown subnodes will be treated as constants always... or something like that.

**Comment by alfoa** [comment]
An issue in the RAVEN repository needs to be created here.

**Comment by PaulTalbot-INL** [comment]
> An issue in the RAVEN repository needs to be created here.

Can an issue in a plugin not be justification for a PR in RAVEN? Not that we don't have this problem in RAVEN (see #84, #936), but in principle, does the issue have to be in RAVEN itself, philosophically/technically speaking?

**Comment by alfoa** [comment]
If I understood correctly, this modification would allow for misspelling nodes (that are supposed to be checked). Is it correct? 

For example, If I have a node supposed to call "myNode" and I call it "myNose", the node will be accepted as "unknown" and fail later on?

Is it right?

**Comment by alfoa** [comment]
> > An issue in the RAVEN repository needs to be created here.
> 
> Can an issue in a plugin not be justification for a PR in RAVEN? Not that we don't have this problem in RAVEN (see #84, #936), but in principle, does the issue have to be in RAVEN itself, philosophically/technically speaking?

I think we need to have it in RAVEN too (referencing to the plugin issue). Also because we require to test this modification (aka unit testing in this case)

**Comment by dylanjm** [comment]
> For example, If I have a node supposed to be called "myNode" and I call it "myNose", the node will be accepted as "unknown" and fail later on?

@alfoa That should be the default behavior that is caught at run-time and an error showing the user `myNose` is not an allowed parameter. 

This modification would work when users want to add custom subnodes that we, as developers, might not know before hand. In the referenced HERON issue the example is:

We, the developers, add an optional `case_info` node that can be populated with static information to help identify runs with associated output data. Such as:

```xml
<Case>
...
<case_info>
  <state>California</state>
  <mylastname>McDowell</mylastname>
...
</case_info>
```

We can't declare `state` and `mylastname` as InputParameters so we provide a way to let a Node have an unknown number of subnodes just as long as they don't mean anything to actual model computation.

**Comment by dylanjm** [comment]
After talking with @PaulTalbot-INL we are going to go a different direction with handling this static information. It does appear `strict` and `unknownSubs` are duplicates and can probably be phased out eventually. I'll go ahead and close this PR.

**Pull request closed without merging**
