### PR TITLE
validate xml tools py3 compatible

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Towards #71.

##### What are the significant changes in functionality due to this change request?
Changes `validate_xml.py` and its dependencies to be python3 compatible. Also some linting readability maintenance.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
@joshua-cogliati-inl do you have a minute you could review this py3 update? I think it relates a bit to the migration you've been working on, but it might have fallen through the cracks since we only run validation in a python 2 environment.

**Comment by alfoa** [comment]
@PaulTalbot-INL Can you take a look at the conflicts?
Sorry for this.

**Comment by PaulTalbot-INL** [comment]
Done.

**Comment by alfoa** [comment]
Ahia...there is a failure

**Comment by PaulTalbot-INL** [comment]
Yeah, new non-python3 compatible stuff has been added since my sweep, it looks like. Made a change.

**Comment by alfoa** [comment]
PR check list passed...

Merging...

**Pull request merged**
