### PR TITLE
Fixes version conflict for cloudpickle

### PR DESCRIPTION
**Pull request by j-bryan**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#2355 

##### What are the significant changes in functionality due to this change request?
Dask was the offending package, with dask version 2024.8.1 requiring cloudpickle >= 3.0.0. Reverting to 2024.8.0 resolves this issue. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Review by dylanjm — DISMISSED** [review]
Changes approved. These changes are required to update RAVEN/HERON on HPC.

**Comment by dylanjm** [comment]
@j-bryan Looks like there is now a diff on a HERON test for HERD. We will have to look into that and prepare a submodule update for HERON with a regolded or fixed test.

**Comment by j-bryan** [comment]
@dylanjm It looks like the errors on the HERD test are really small (~10^-9). A regold or just adding a tolerance to the test should be fine. Also, it looks like it's a different plugin test failing on Mac, one of the LOGOS tests. @wangcj05, any insights on that LOGOS test?

**Comment by wangcj05** [comment]
> @dylanjm It looks like the errors on the HERD test are really small (~10^-9). A regold or just adding a tolerance to the test should be fine. Also, it looks like it's a different plugin test failing on Mac, one of the LOGOS tests. @wangcj05, any insights on that LOGOS test?

@j-bryan The logos tests are fine, the failure is caused by time out, which happens.

**Comment by dylanjm** [comment]
@j-bryan Okay great, yeah once this is merged we can regold that HERON test.

**Comment by dylanjm** [comment]
We keep getting the following error on the python environment setup @joshua-cogliati-inl any thoughts why this is happening?

``` 
... Activating environment ...
... conda-forge command: mamba install -y -c conda-forge h5py numpy=1.22 scipy=1.9 scikit-learn=1.0 pandas xarray=2023 matplotlib=3.5 statsmodels=0.13 cloudpickle python=3 hdf5 swig pylint coverage lxml psutil pip pyDOE3 importlib_metadata nomkl smt statsforecast setuptools=69 numpy-financial networkx pytest dill=0.3.5 pyomo=6.4 pyutilib glpk ipopt coincbc=2.10.5 cvxopt quadprog qpsolvers
Traceback (most recent call last):
  File "/home/civet/.conda/envs/raven_libraries/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.9/site-packages/mamba/mamba.py", line 44, in <module>
    import libmambapy as api
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.9/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.9/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory

ERROR: exiting with code 1
```

**Comment by wangcj05** [comment]
duplicated pr.

**Pull request closed without merging**
