### PR TITLE
Add "long" data type compatability

### LINKED ISSUE #589: csv input reader in windows
--------
Issue Description
--------
##### What did you see instead?
In windows:
The input reader for csv does not convert integers to reals, which generates an error in the history set.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Should close #589 for the dataobject-rework branch, but we will need to see it pass on Windows especially.

##### What are the significant changes in functionality due to this change request?
Adds the `long` data type to the acceptable integer data types.  Tested through the mathUtils unit tests.  The test integer was selected based on a number that was too long to be merely an integer on OS X 10.12.6 using python 2.7.13 64-bit.

### CODE REVIEW

**Comment by alfoa** [comment]
@PaulTalbot-INL is this a problem that affects the dataobject-rework branch only or it affects devel as well?

**Comment by alfoa** [comment]
ok I saw that in the issue you specified it affects  dataobject-rework only

**Comment by PaulTalbot-INL** [comment]
From what I can tell, we always cast entries as "floats" in the old scheme; it wasn't until the rework that we started allowing more types.

**Comment by alfoa** [comment]
@PaulTalbot-INL I took a look at the test failing in Linux. there are several diffs  and some crashes.
Some of the diffs look like are related to the "old behavior" of the pandas print  => index printed in the format ```(0.0,)``` instead of ```0.0```

**Comment by PaulTalbot-INL** [comment]
I can get a wide variety of responses depending on the numpy, xarray, and pandas library version.  I'm looking into the best way to work with this.

**Comment by PaulTalbot-INL** [comment]
This needs to rerun tests after #595 is merged.

**Comment by AaronEpiney** [comment]
@PaulTalbot-INL. As you asked me, I verified the following on my RAVEN windows installation:
- checked out branch workshop_201803 (data rework based branch) and run test input ./raven/doc/workshop/ARMA/test/train_arma.xml 
   → can confirm 'type long' error
```
(    0.11 sec) HistorySet               : ERROR           -> Unrecognized data type for var "scaling": "<type 'long'>"
```
- merged fix talbpaul/windows-long-fix and the test completes without error. After merging the fix, RAVEN asked me to update some libraries, which I did before running the test.

**Comment by PaulTalbot-INL** [comment]
Perfect!  Thanks for your help, and sorry for the headaches it may have caused prematurely.

**Comment by alfoa** [comment]
@PaulTalbot-INL The tests on Linux are failing. Do you have an idea why?

**Comment by PaulTalbot-INL** [comment]
The Windows tests are failing because it can't check out CashFlow due to the HPC outage, for the record.

**Comment by alfoa** [comment]
did you check locally that Windwos passes?

**Comment by PaulTalbot-INL** [comment]
I'm still having an issue with the grid forward sampling, I'm looking into it.  I'll let you know when it clears.

**Comment by alfoa** [comment]
@derekstucki The Windows machine (even if the tests completed) does not return and it is shown as "pending"

**Comment by alfoa** [comment]
@derekstucki  and in the MAC machine, the following libraries are not found:
```

pandas not found

xarray not found

netCDF4 not found
```
but the step is tagged as green. Probably the script does not return an error code. We have to fix this.
Thanks

**Comment by alfoa** [comment]
The MAC machine needs to be fixed. The others show the green light.
Merging

**Pull request merged**
