### PR TITLE
Removing sort from RELAPparser.py 

### PR DESCRIPTION
**Pull request by Jimmy-INL**
--------
The PR addresses issue #995, by removing the sort from RELAPparser.py.
In addition, a typo was corrected in the user manual, under runInfo.tex: the <estimatedTime> was defined as colon separated string instead of column separated. 
--------
Ref. #995.

Ref. #995

No change in functionality, and regression tests for the RELAP interface passed (at least on my machines).

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

Screen Shot 2019-07-22 at 1 14 38 PM

### CODE REVIEW

**Comment by wangcj05** [comment]
@Jimmy-INL The issue #995 was addressed in PR #996, you may consider to merge your PR with PR #996, please talk to @PaulTalbot-INL. In addition, there are some questions regarding the issue #995  closure checklist. Please try to resolve that issue.

**Comment by PaulTalbot-INL** [comment]
Since this involves changing exactly 8 characters in 1 line, I don't think combining the pull requests in some way makes much sense. I'll close the other pull request, as @Jimmy-INL will have the resources to properly address the concerns @wangcj05 has raised in the issue closure process.

**Comment by wangcj05** [comment]
Tests failed, and I believe our devel will have similar issues:
1. framework/ROM/SKLearn/GP: we need to increase the error tolerance (small diff for Linux systems)
2. timeout for varma test
3. qsub test failed for adapted sobol
@alfoa  @PaulTalbot-INL

**Comment by Jimmy-INL** [comment]
I have loosened up the tolerance of the GP test.


Let me know if there are further actions needed. Also, I remember you suggested using this PR as a guinea pig to test the machines since it is a shallow PR.

________________________________

**Comment by alfoa** [comment]
Ok guys,
I changed the base of this PR from devel to a branch I just created. Unfortunately there is another problem with RELAP5 interface that has been discovered during the workshop.

I will address it there (and merge this PR in that branch)

**Pull request merged**
