### PR TITLE
Excel BOM fix

### LINKED ISSUE #1564: [DEFECT] Pointset does not load a variable in the first column of a csv.
Issue being that the system does not load the variable Time in the first column of the csv. 

Error is below. Shows missing Tb and Tb as being unused. 

RAVEN Python dependencies located and checked.
(    2.99 sec) SIMULATION               : Message         -> Simulation started at 2021-05-19 15:59:39
InputData: Using param spec "DataSet" to read XML node "PointSet.
(    3.05 sec) PointSet                 : ERROR           -> Not all variables requested for data object "data" were found in csv "C:\Users\FRICKL\projects\TEDS_VandV\V_V\csv\TEDS_startup.csv"!
Needed: {'Tb', 'Flow Rate'};
Unused: {'Type K TC #1', 'Tb', 'Omega Pressure', 'Date/Time', 'Type K TC #3', 'Type K TC #2'};
Missing: {'Tb'}
OSError: Not all variables requested for data object "data" were found in csv "C:\Users\FRICKL\projects\TEDS_VandV\V_V\csv\TEDS_startup.csv"!
Needed: {'Tb', 'Flow Rate'};
Unused: {'Type K TC #1', 'Tb', 'Omega Pressure', 'Date/Time', 'Type K TC #3', 'Type K TC #2'};
Missing: {'Tb'}

**Describe how to Reproduce**
1.  unload the zip. [issue.zip](https://github.com/idaholab/raven/files/6511792/issue.zip)
2. make a csv folder and place the .csv file in there.
3.  run the .xml file in a directory above the csv folder. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1564 

##### What are the significant changes in functionality due to this change request?
Removes the Excel BOM from the start of a CSV file if detected when there's no meta XML to work with.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Review by dylanjm — COMMENTED** [review]
Just a quick question on the logic. 

If the `line` starts with the variable `\ufeffVARIABLE1` would it it then skip that variable completely by using the `line[1:]` indexing?

Or is it always the fact that `\ufeff` by itself is the first variable?

**Comment by PaulTalbot-INL** [comment]
it appears to me that `\ufeff` is a single character in the string; in Konor's case, the line started with `\ufeffTb` and it still preserved the `Tb`.

**Comment by dylanjm** [comment]
@PaulTalbot-INL Ahh okay, so it's seeing `\ufeff` as a single character. That's where my confusion was coming from.

**Review by dylanjm — APPROVED** [review]
Looks good. This is a small code change so no documentation or tests were needed.

**Comment by dylanjm** [comment]
I'm going to go ahead and merge this since I believe the OpenSUSE tests are still broken.

**Pull request merged**
