### PR TITLE
PRA plugin fixes

### LINKED ISSUE #822: PRA plugin test issues
--------
Issue Description
--------
##### What did you see instead?
Two tests have the first run failed:
test_ensemblePRAModel_discrete.xml
test_ensemblePRAModel_mixed.xml

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by mandd**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #822 
New gold tests have been manually checked

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by wangcj05** [comment]
Two tests failed on mac:
```
    DIFF doc/workshop/forwardSampling/Inputs/previous.FS6 FAILED (In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X2_X2" don't match
	rel diff:  1.0 ~ -0.199999999999 = 1.2
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X2_X1" don't match
	rel diff:  -0.2 ~ 0 = 1.0
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X1_X1" don't match
	rel diff:  1.0 ~ 0 = 1.0
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X1_Y2" don't match
	rel diff:  1.42857142857 ~ 1.0 = 0.299999999999
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y2_Y2" don't match
	rel diff:  1.0 ~ 0 = 1.0
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y1_X2" don't match
	rel diff:  -180.094328315 ~ 1.0 = 1.00555264571
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y1_X1" don't match
	rel diff:  973.978473545 ~ -180.094328315 = 1.18490586107
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y2_X1" don't match
	rel diff:  0.7 ~ 1.0 = 0.3
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y1_Y1" don't match
	rel diff:  1.0 ~ 973.978473545 = 0.998973283263
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X2_Y1" don't match
	rel diff:  0 ~ 1.0 = 1.0
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_Y2_Y1" don't match
	rel diff:  0 ~ 0.7 = 1.0
In r6/Stat_basicStatPP_dump.csv: The values in column "sen_X1_Y1" don't match
	rel diff:  0 ~ 1.42857142857 = 1.0
)
    DIFF framework/ROM/SKLearn.OCC FAILED (
DIFF in /Users/civet/civet/build_0/raven/tests/framework/ROM/SKLearn/data/outOCC.csv: 
  Could not find match for row "1" in Gold:
X                       2.0000
Y                   -1000.0000
Z                       1.0000
ProbabilityWeight       0.0025
dtype: float64
  The Test output csv is:
         X       Y  Z  ProbabilityWeight
0    2.0 -1000.0  0             0.0025
```

The first one is know issue, and the second one is recently reported within raven development team.

**Comment by wangcj05** [comment]
@mandd Can you rebase your PR? The failed tests should pass now.

**Comment by mandd** [comment]
testing now on my local machine just to be 100% sure

**Comment by wangcj05** [comment]
This PR is good to me. @alfoa any comment on this PR?

**Comment by alfoa** [comment]
Checklist passed...

PR can be merged...

Merging...

**Comment by alfoa** [comment]
Test qsubs and Test OpenSUSE Tumbleweed are down now, so they do not impact the validity of this PR

**Pull request merged**
