### PR TITLE
rework: Multilevel optimizers

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Fixes the multilevel optimizers for the dataobject rework.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
```
**** THE FOLLOWING TESTS CHANGED OUTCOMES ****
**** Test framework/Optimizers.Infinite | has changed outcome from <FAILED> to <OK> !!!!
**** Test framework/Optimizers.MultiLevelWithMultiTrajectory | has changed outcome from <FAILED> to <OK> !!!!
*****************
**** THE FOLLOWING TESTS HAVE BEEN REMOVED IN 2ND FILE ****
**** Test framework/ROM/TimeSeries.ARMAreseedTest | has been REMOVED! It is present in 1st file BUT NOT in 2nd file !!!!
*****************
**** THE FOLLOWING TESTS HAVE BEEN ADDED IN 2ND FILE ****
**** Test framework/ROM/TimeSeries.ARMAreseedTest.......................................... | has been ADDED  ! It is present in 2nd file BUT NOT in 1st file !!!!
*****************
Number of success first file:
461
Number of success second file:
463
NUMBER OF SUCCESSES INCREASED: +2
TOTAL TIME OF TESTS INCREASED       : reference_time(593.5) < new_time(601.5)
AVERAGE TIMES FOR SUCCESS TESTS ARE : reference_time(1.2874186551) v.s. new_time(1.29913606911)
*********************************
```

**Comment by PaulTalbot-INL** [comment]
One more passing test now:
```
(talbpaul/rework-ML-opt) inl602304:~/projects/main_raven>./run_tests --re=framework.Optimizers.Pre
/opt/moose/miniconda/bin/conda
/Users/talbpw/projects/main_raven/scripts/copy_plugins_tests.py:34: UserWarning: The plugin "/Users/talbpw/projects/main_raven/plugins/CashFlow" does not contain a "tests" directory!
  warnings.warn('The plugin "'+plugin_dir+'" does not contain a "tests" directory!')
framework/Optimizers.Preconditioner....................................................................... OK
-------------------------------------------------------------------------------------------------------------```

**Comment by wangcj05** [comment]
@alfoa Any comments on this PR?

**Comment by wangcj05** [comment]
This can be merged now

**Pull request merged**
