### PR TITLE
Value at risk correction

### LINKED ISSUE #1749: [DEFECT] valueAtRisk in EconomicRatio is calculated incorrectly
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Value at risk is defined as the negative of a specified quantile. The code takes the absolute value.

### Steps to Reproduce

The issue is seen when using a distribution that is always positive. The value at risk should give a negative value, however the code always returns a positive value.

### Expected Behavior

When the specified quantile is negative, value at risk should return a positive value. When the specified quantile is positive, value at risk should return a negative value.

### Screenshots and Input Files

_No response_

### OS

Windows

### OS Version

_No response_

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by dgarrett622**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

Fixes #1749 

##### What are the significant changes in functionality due to this change request?

- Value at Risk is calculated correctly as negative of a quantile instead of absolute value of quantile
- Additional bug fixed in calculating sortinoRatio that allows calculation to not throw error
- Updated user manual entry for valueAtRisk

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Review by PaulTalbot-INL — DISMISSED** [review]
I have no issue with any of your changes. I have some concerns about code coverage on the daMed change, but that may be beyond scope of this PR.

**Comment by dgarrett622** [comment]
Email draft for users:

Dear users,

An issue has been identified with the Value at Risk calculation in the EconomicRatio PostProcessor. An absolute value was taken instead of the negative of the value. PR #1751 corrects this calculation.

**Comment by PaulTalbot-INL** [comment]
As per discussion this morning, a warning should be added when the VaR is negative, explaining simply how to interpret this; so we will wait to merge until that is added.

**Review by PaulTalbot-INL — APPROVED** [review]

**Comment by PaulTalbot-INL** [comment]
All required tests have passed. Merging.

**Comment by PaulTalbot-INL** [comment]
@dgarrett622 can you send the user email, or ask @wangcj05 to do so? Thanks!

**Comment by dgarrett622** [comment]
User email has been sent.

**Pull request merged**
