### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by alfoa**
Added some names for the proposed assignees

### CODE REVIEW

**Review by wangcj05 — APPROVED** [review]
No code change, just update issue template.

**Comment by wangcj05** [comment]
@alfoa where is the related issue, the PR description and the checklist?

**Comment by PaulTalbot-INL** [comment]
I don't love auto-assignment; I like to be assigned to issues that I will be handling immediately, not a backlog of assignments that I may or may not ever get to. I think no default assignees is much better than having everyone assigned to every issue; we already have problems with multiple people fixing the same issue at once as it is.

**Comment by alfoa** [comment]
Unfortunately i released that "no default" determined that there are several issues that we did not even "reviewed". The initial default assignment is to notify (Forcefully) everyone that a new Defect is out there (I changed this for defects only...I hope we do not get 10 issues per day). what do you think?
Andrea

**Pull request merged**
