### PR TITLE
rework: fixed rrr example plugin test

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Fixes the raven-running-raven example plugin test.

### CODE REVIEW

**Comment by wangcj05** [comment]
Could you post the test results for plugin tests?

**Comment by PaulTalbot-INL** [comment]
Note that fixes for the CashFlow plugin are in Merge Request 7 for that repository.

**Comment by PaulTalbot-INL** [comment]
Test comparison results:

```
**** SUMMARY ****
*********************************
**** THE FOLLOWING TESTS CHANGED OUTCOMES ****
**** Test plugins/ExamplePlugin.TestPluginWithRavenRunningRaven | has changed outcome from <FAILED> to <OK> !!!!
**** Test plugins/ExamplePlugin/tests.TestPluginWithRavenRunningRaven | has changed outcome from <FAILED> to <OK> !!!!
*****************
Number of success first file:
478
Number of success second file:
480
NUMBER OF SUCCESSES INCREASED: +2
*********************************
```

**Comment by wangcj05** [comment]
This tests is good to go. In addition, could you share the test results with us? @PaulTalbot-INL

**Pull request merged**
