### PR TITLE
Jimmy adding pysensors to dependencies

### LINKED ISSUE #1679: [TASK] Adding PySensors library to RAVEN
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
This is not related to a problem, but it facilitates the optimization of sparse sensors in Nuclear applications.

**Describe the solution you'd like**
I'd like to be able to use the PySensors algorithms within RAVEN

Note that this will require updating to scikit-learn 0.24 or newer.

**Describe alternatives you've considered**
reimplement the algorithms from scratch.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by Jimmy-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1679 

##### What are the significant changes in functionality due to this change request?
Added sensors to the dependencies. This is step towards implementing the sparse learning Postprocessor

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by Jimmy-INL** [comment]
@joshua-cogliati-inl, I guess this is ready to go.

**Comment by Jimmy-INL** [comment]
@wangcj05 this is a one-line code change, all tests are green.

**Comment by wangcj05** [comment]
@Jimmy-INL I suggest not merge it since RAVEN is not using pysensor right now.

**Comment by Jimmy-INL** [comment]
OK, that makes sense.
I will then add this line to my other branch implementing the Sparse Sensing PP.
Thanks.

Mohammad G. Abdo, Ph.D.
Modeling and Simulation Scientist   |  Digital Reactor Technology and Development (C160)
Reactor Systems Design and Analysis   |   NS&T
***@***.******@***.***>   |  REC EROB IF-654 3EM402  |  Phone: 208-526-4640
Idaho National Laboratory   |   2525 Fremont Ave.   |   Idaho Falls, ID   |   83415
[6GC4jc7QCCEAAAAASUVORK5CYII=]<https://www.linkedin.com/in/mohammad-abdo-a7625082/>.               [PXly9OZ1PK9LcRv4PSG3pAb9jevQAAAAASUVORK5CYII=] <https://www.researchgate.net/profile/Mohammad_Abdo/research>                 [RPr5ytnPx9Cc691m9I+4T+nIo7v4HxgxndxMwKP8AAAAASUVORK5CYII=] <https://github.com/Jimmy-INL>
___________________________________
[wYtJH347IiIiAYVYS1skEvgxC4KpkYRTFRBbsT51peEIp5j0ExRuvWouzr1J+za4DYirM+SlQmTZXUTsvjtVtouILWngWSxC+xJbAP86Fg5oVmy2ERH1w38A8nnHfeT8na8AAAAASUVORK5CYII=]


From: Congjian Wang - INL ***@***.***>
Date: Thursday, May 26, 2022 at 11:15 AM
To: idaholab/raven ***@***.***>
Cc: Mohammad G. Abdo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] Jimmy adding pysensors to dependencies (PR #1839)

@Jimmy-INL<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJimmy-INL&data=05%7C01%7Cmohammad.abdo%40inl.gov%7C843f5160e6b4457b356a08da3f3b6004%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637891821492200647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HFz%2FqKj6mgZqDSQUKsGkZHItqFXqvW5fpb032TX%2BS5M%3D&reserved=0> I suggest not merge it since RAVEN is not using pysensor right now.

**Comment by wangcj05** [comment]
@Jimmy-INL I think this PR is replaced by PR #1931

**Pull request closed without merging**
