### PR TITLE
[HERON] use https instead of ssh for submod

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes https://github.com/idaholab/HERON/issues/8

##### What are the significant changes in functionality due to this change request?
Moves HERON to using https instead of ssh for installing as a submodule

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by klfrick2** [comment]
This proposed fix has solved the issue I was having. Thanks!

**Comment by PaulTalbot-INL** [comment]
Given that CIVET is currently available, I checked out devel, cleaned, installed HERON and TEAL plugins, ran conda install, ran build, and ran both tests and plugin tests.

All tests passed except some LOGOS and SRAW tests (who need CashFlow changed; I haven't connected to update those plugins on my machine yet).

**Comment by Jimmy-INL** [comment]
Last time we discussed you told me you will not get to it now, and you will let me know as you get back to it.
I recall that I pointed out that the ssh is still being used because it was in one of the .git files

**Comment by PaulTalbot-INL** [comment]
I don't recall that, sounds like an issue local to your installation, maybe? I still need this merged for users, for sure.

**Comment by Jimmy-INL** [comment]
In the .gitmodules:

[submodule "plugins/SR2ML"]
       path = plugins/SR2ML
       url = git@hpcgitlab.hpc.inl.gov:RAVEN_PLUGINS/SR2ML.git
[submodule "plugins/LOGOS"]
       path = plugins/LOGOS
       url = git@hpcgitlab.hpc.inl.gov:RAVEN_PLUGINS/LOGOS.git
[submodule "plugins/SRAW"]
       path = plugins/SRAW
       url = git@hpcgitlab.hpc.inl.gov:RAVEN_PLUGINS/SRAW.git
[submodule "plugins/TEAL"]
       path = plugins/TEAL
       url = https://github.com/idaholab/TEAL.git
[submodule "plugins/HERON"]
       path = plugins/HERON
       url = git@github.com:idaholab/HERON.git

**Comment by PaulTalbot-INL** [comment]
Check the files changed as part of this PR again, please. It changes the access from using ssh to http for HERON. You highlighted the one from TEAL, which is correct and doesn't need changing.

**Comment by Jimmy-INL** [comment]
Paul I can merge it if you want, but as I am telling you in the files changed it is correct but I think it is overwritten by .gitmodules which only has thew ssh.

**Pull request merged**
