### PR TITLE
downgrade python

### PR DESCRIPTION
**Pull request by wangcj05**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
see #1036 

fix python version to 3.7.3, since there is a build issue for python 3.7.4 in conda, we will remove the restriction when the issue in python 3.7.4 is resolved

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wangcj05** [comment]
@PaulTalbot-INL Could you take a look at this PR?

**Comment by PaulTalbot-INL** [comment]
This merge is a temporary rollback until a fix can be done. Approved to merge if/when tests pass without further modification.

**Comment by PaulTalbot-INL** [comment]
Note: an email should be sent to the user list once this is merged, requesting re-installation of libraries and recompiling using the scripts.

**Comment by wangcj05** [comment]
Dear RAVEN Users,

We have recently found an issue in the latest version of python (python 3.7.4) build in conda that could cause the module import error in RAVEN for all linux-type machines:
```
Traceback (most recent call last):
  File "test_import.py", line 20, in <module>
    import crow_modules.distribution1Dpy3
  File "/home/civet/civet/build_0/raven/crow/install/crow_modules/distribution1Dpy3.py", line 17, in <module>
    _distribution1Dpy3 = swig_import_helper()
  File "/home/civet/civet/build_0/raven/crow/install/crow_modules/distribution1Dpy3.py", line 16, in swig_import_helper
    return importlib.import_module('_distribution1Dpy3')
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_distribution1Dpy3'
```

There is an open issue in anaconda to fix the bad build python (https://github.com/ContinuumIO/anaconda-issues/issues/11195). We will keep track of this issue until it was fixed.

For now, we have locked the python version to 3.7.3. In the meantime, if you experience the same errors as mentioned before. Please try to pull the latest changes, clean raven, and reinstall raven_libraries and rebuild raven. Please let us know if you have any problems.

@PaulTalbot-INL  Here is the draft email.

**Comment by joshua-cogliati-inl** [comment]
Tests pass, merging

**Pull request merged**
