### PR TITLE
MultiRun Step Reorganization

### LINKED ISSUE #366: Collection/Submission deadlock in MultiRun Step
--------
Issue Description
--------
It is possible to deadlock RAVEN in a MultiRun step if 1) the JobHandler is finished, 2) the Sampler has more points to provide, and 3) there are no new inputs to collect.  Thus far this hasn't occurred, but with killing jobs before they are collected, it is possible to get stuck in an infinite while loop.

It is recommended we flatten the collection and submission loop to:
 - Increase readability of the step,
 - Align code logic with reasonable expected behavior,
 - Prevent accidental locking/infinite loops.

This PR is necessary in order to have efficient parallel gradient operations developed for the SPSA.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #366.

##### What are the significant changes in functionality due to this change request?
Flattens the MultiRun step to allow collections and/or submissions on every loop in the "run" main thread.

As a result, it was necessary to increase the sleep time of some tests in order to maintain the same one-at-a-time performance as observed previous to this PR.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by alfoa** [comment]
@PaulTalbot-INL I think here we need to review this when we have a bit more time... the number of re-golding is huge and you needed to set the sleepTime to some of the tests == 0.1 seconds... 

I am sure the development is correct but there is something we need to understand first...

What do you think? Do you need this to be merged now?

**Comment by PaulTalbot-INL** [comment]
This needs to be merged only as urgently as we need parallel gradient evaluations.  I moved the test with the long sleep time to a heavy test, since 1) it is testing a feature you want to remove, and 2) the sleep time needed to be large to get linear behavior.

I don't think there's really anything to investigate, unless we want to develop a "sequential" mode for raven that will not depend on processor speed, parallelism, etc.

**Comment by alfoa** [comment]
I think that all these failures are indications that there is something to investigate...

**Comment by PaulTalbot-INL** [comment]
Yes, "all these failures" are described by the lack of sequential requirement that our code has, as we've discussed several times.  I look forward to your findings.

**Comment by PaulTalbot-INL** [comment]
This needs to be reconsidered if needed and branched from RAVEN 1.1.  Closing.

**Pull request closed without merging**
