### PR TITLE
fixed conflicts

### PR DESCRIPTION
**Pull request by alfoa**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Fixed conflicts

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
Apparently conda/numpy has some library confusion:

https://stackoverflow.com/questions/36659453/intel-mkl-fatal-error-cannot-load-libmkl-avx2-so-or-libmkl-def-so

Trying a couple versions to see what sticks.  I can't get this error to show up on my mac.

**Comment by PaulTalbot-INL** [comment]
As with pulling one loose thread in a sweater, the library changing has snowballed into quite an effort.  I think I have a set that work together locally and are closer to current, but a few tests are failing that I need to investigate locally.

**Comment by PaulTalbot-INL** [comment]
Updating conda tanked everything I had.

It turns out, the procedure for making conda available via bashrc changed between 4.3 and 4.4.

Old way (4.3.21, for example):
```bash
export PATH="/Users/talbpw/miniconda2/bin:$PATH"
```
New way (4.4.11, for example):
```bash
. ~/miniconda2/etc/profile.d/conda.sh
```
This restored my libraries.  This conversion may be necessary if we require updating to conda 4.4 from 4.3 for users.

**Comment by alfoa** [comment]
@PaulTalbot-INL if it passes, we should ask @derekstucki to update the libraries in the windows machine.

**Comment by PaulTalbot-INL** [comment]
Falcon tests only failed the ARMA reseed test, which is not yet consistent so I think this counts as success.

**Comment by PaulTalbot-INL** [comment]
The reseed arma test has an issue outstanding related to it (#597), and should not hold back this merge.  I will temporarily disable the test.

**Pull request merged**
