### PR TITLE
unnecessary change

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Do not merge

Testing regression testers.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
This is a splendid unnecessary change and I highly unapprove it.

**Comment by PaulTalbot-INL** [comment]
yeah, trying to find out if the ExternalRay test fails on devel or just on Caleb's PR.

**Comment by alfoa** [comment]
> yeah, trying to find out if the ExternalRay test fails on devel or just on Caleb's PR.

also in my PR :(

**Comment by alfoa** [comment]
> @PaulTalbot-INL @joshua-cogliati-inl I think the reason is that redis got a new release yesterday:
> 
> https://pypi.org/project/redis/#history
> 
> And in the dependencies.xml file redis for windows is not pinned to a certain version

downgrading the redis library to 5.1 does not help. No idea!

**Comment by PaulTalbot-INL** [comment]
This PR served its testing purpose and can be closed.

**Pull request closed without merging**
