### PR TITLE
rework: getpot test

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Fixes the getpot test by adding the "what" parameter to the output.

### CODE REVIEW

**Comment by wangcj05** [comment]
The getpot test run result should be reported here.

**Comment by PaulTalbot-INL** [comment]
It's coming shortly.

**Comment by PaulTalbot-INL** [comment]
```
**** SUMMARY ****
*********************************
**** THE FOLLOWING TESTS CHANGED OUTCOMES ****
**** Test framework.getpot_with_externalXML | has changed outcome from <FAILED> to <OK> !!!!
*****************
Number of success first file:
459
Number of success second file:
460
NUMBER OF SUCCESSES INCREASED: +1
*********************************
```

**Comment by wangcj05** [comment]
This can be merged, no code modification.

**Pull request merged**
