### PR TITLE
[WIP] MOOSE regression test system

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Requeset Description
--------
##### What are the significant changes in functionality due to this change request?
Switches to using files from MOOSE revision 786576deef33a317e654558f39f5f45617c7442b instead of a submodule.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by alfoa** [comment]
Joshua,

Thank you very much to try this out as I requested. I tried the branch and it works in my local machine.

Before proceeding we have to talk to Paul Berg because this this portion of the regression system should be placed in our ```contrib``` directory in a separate folder (where we clearly indicate the moose LICENSE, COPYRIGHT, and where we clearly state that we use the MOOSE regression test system in order to give the rightful credits  to the MOOSE project) 

Thank you again 

Andrea

**Comment by joshua-cogliati-inl** [comment]
Note that this should probably be discussed at a meeting or mailing list before being approved.

**Comment by PaulTalbot-INL** [comment]
Did this get approved for reviewing, or does it need further team discussion?

**Comment by alfoa** [comment]
Still under discussion.

**Comment by joshua-cogliati-inl** [comment]
Still under discussion.  At minimum, we need to solve the technical problem of how to easily update when MOOSE changes.

**Comment by alfoa** [comment]
@joshua-cogliati-inl do we wanna close this? So we move to the "new" system shortly.

**Comment by alfoa** [comment]
Closing...

**Pull request closed without merging**
