### PR TITLE
Default to Python 3

### LINKED ISSUE #953: Default to Python 3
--------
Issue Description
--------
##### What did you expect to see happen?
RAVEN to use Python3 unless explicitly asked for python2

##### What did you see instead?
Python 2 is the default.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #953 

##### What are the significant changes in functionality due to this change request?

- `establish_conda_env.sh --install` now defaults to Python 3 without needing the `--py3` argument.  In order to install Python 2, use `establish_conda_env.sh --install --py2` 
- There is a new environmental variable `PYTHON_COMMAND` that specifies the python command that is to be used (such as `python3.6.exe`)  This is also stored in the `.ravenrc` file and is loaded with `establish_conda_env.sh`   Note that in conda on all operating systems and in the Python.org version of Python for windows `python` can be used as the python 3 command; `python3` is not needed.
- The environmental variables `CHECK_PYTHON3` and `CROW_USE_PYTHON3` are no longer used.  `PYTHON_COMMAND` should be used instead if specifying a specific Python command is needed for setup or running.  Note that `PYTHON_COMMAND` can be used even if `establish_conda_env.sh` is not used, but in that case, it will not be automatically loaded from `.ravenrc`
- `run_tests` now supports `--skip-conda` as a parameter to not use conda.
- The `clean_raven` script has been added to remove build files.
- `setup.py` has been modified so it builds for Python 3 if it is called with Python 3.

The following files have been removed:
```
build_framework
amsc.mk
raven.mk
Makefile
crow/Makefile
crow/config.mk
crow/crow.mk
crow/crow_python_modules.mk
setup3.py
crow/setup3.py
```

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
@alfoa or @PaulTalbot-INL or @wangcj05 

This is ready to review.

**Comment by PaulTalbot-INL** [comment]
I did a pass on the code and found nothing objectionable, although clearly several odd behaviors were encountered and overcome to make the system work again.

The internal documentation appears to be modified; was the wiki changed as well?

**Comment by joshua-cogliati-inl** [comment]
@PaulTalbot-INL I did review the internal wiki.  After this goes in the https://github.com/idaholab/raven/wiki/python3Installation page needs to be modified to state that Python3 is the default, and probably a Python2 page needs to be added as well that documents the --py2 flag.

**Comment by PaulTalbot-INL** [comment]
A user notification is missing before the associated issue can be closed. I would appreciate confirmation on the changes from the CCB Chair @alfoa before moving forward, as well.

All other requirements have been met to my satisfaction.

**Comment by PaulTalbot-INL** [comment]
Merging. The email should be sent and the wiki updated. 

Thanks! This is significant progress.

**Comment by joshua-cogliati-inl** [comment]
wiki updated.

**Pull request merged**
