### PR TITLE
WIP: Alfoa/logical model and ensemble

### PR DESCRIPTION
**Pull request by alfoa**
--------
Pull Request Description
--------
##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wangcj05** [comment]
@alfoa @mandd I have fixed the problem of the collection crash and fixed some typos in the test. Now we can run the logical model within ensemble model. We still need to fix the issue regarding the multi-level client queue. For now, in order to run the test, the batch size should >= limit (MC sampler) + 1.

**Comment by joshua-cogliati-inl** [comment]
> @alfoa @mandd I have fixed the problem of the collection crash and fixed some typos in the test. Now we can run the logical model within ensemble model. We still need to fix the issue regarding the multi-level client queue. For now, in order to run the test, the batch size should >= limit (MC sampler) + 1.

Hm, looking at the multi-level client queue problem, ```sampler.amIreadyToProvideAnInput()``` is True, but ```jobHandler.availability(True)``` is 0.

**Comment by joshua-cogliati-inl** [comment]
I think the best way is to replace this code:
```python
          while not moveOn:
            if jobHandler.availability() > 0:
              # run the model
              #if modelIn not in modelsOnHold:
              self.raiseADebug('Submitting model',modelIn)
              self.modelsDictionary[modelIn]['Instance'].submit(originalInput[modelIn], samplerType, jobHandler, **inputKwargs[modelIn])
              # wait until the model finishes, in order to get ready to run the subsequential one
              while not jobHandler.isThisJobFinished(modelIn+utils.returnIdSeparator()+identifier):
                time.sleep(1.e-3)
              nextModel = moveOn = True
            else:
              time.sleep(1.e-3)
          # store the results in the working dictionaries
            returnDict[modelIn] = {}
```
Notice how it dumps something in a jobHandler queue, and then busy waits until it is done?
Instead, it should just directly call the method since there is no advantage to running it later if we will just wait until it is done.  This is easier said than done since the surrounding code expects it to be a runner object.

**Comment by aalfonsi** [comment]
@wangcj05 @joshua-cogliati-inl ? what do you want to do with this?

**Comment by wangcj05** [comment]
> @wangcj05 @joshua-cogliati-inl ? what do you want to do with this?

@aalfonsi I think you have fixed the problem in EnsembleModel, and I think we need to find the resources to fix the problems in HybridModel.

**Pull request closed without merging**
