### PR TITLE
rework: test harness fix

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Fixes test harness to remove output files before running tests.

Also fixes MC restart case.

### CODE REVIEW

**Comment by PaulTalbot-INL** [comment]
It appears we now have a library problem on the linux machines; they can't find pandas.  This should not be possible due to our setup script, but apparently it's happening.

**Comment by wangcj05** [comment]
@PaulTalbot-INL It seems the library issue have existed for a long time (at the beginning of December, 2017).

**Comment by wangcj05** [comment]
The failure is not because of this PR, and I will merge it.

**Comment by wangcj05** [comment]
Let's fix the library issue in a different PR.

**Pull request merged**
