### PR TITLE
modified the Dymola interface to write the file path of the text file…

### PR DESCRIPTION
**Pull request by dgardner26**
… containing vector info from RAVEN to the Dymola initialization file

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#1903 

##### What are the significant changes in functionality due to this change request?
The interface now writes the path to the file containing vectors passed into Dymola into the Dymola initialization file.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by dgarrett622** [comment]
@dgardner26 the test machines will not run currently due to failed dependencies, here is the error message:

> ##########################################################################
> ERROR: The following files contain trailing whitespace after applying your patch:
> 	ravenframework/CodeInterfaceClasses/Dymola/DymolaInterface.py
> 
> Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
> ##########################################################################

Could you run the `developer_tools/delete_trailing_whitespace.sh` script and push your changes?

**Comment by wangcj05** [comment]
@dgardner26 thanks for your contribution. However, there is some issue with your PR. Could you help us to resolve this issue so that we can merge your PR? Please check the comment from @dgarrett622

**Comment by wangcj05** [comment]
@JunyungKim I have assigned this PR to you. Please let me know if you have any issue.

**Comment by JunyungKim** [comment]
I solved dependency issues which Daniel Garrett mentioned. Another PR #2024 is made and this PR can be closed.

**Comment by JunyungKim** [comment]
This PR is closed: PR 2029 replaces this PR.

**Pull request closed without merging**
