### PR TITLE
Added Apple Silicon compatible dependencies to FARM, tested on M1 MacBook Pro

### PR DESCRIPTION
**Pull request by wanghy-anl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#1114 
#2138 
#2158 
This version of FARM submodule can install and pass all the tests on Intel-based Windows 10, Intel-based Ubuntu 18.04, Intel-based MacBook Pro, and Apple M1 based MacBook Pro.

##### What are the significant changes in functionality due to this change request?
Added "pip" source for `fmpy`, and added "forge" source for `qpsolvers`
Also corrected some minor bugs in FARM-Delta

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wanghy-anl** [comment]
Hello, could anyone share the details of the failed tests? This commit will have 3 raven tests to fail on Mac computers with M1/M2 CPU, but should pass all the tests on Windows, Intel-based Mac and Ubuntu 18.04. I clicked on the "Details" link but it says "You are not allowed to see results. Please sign in to an appropiate user." Thanks.

**Comment by wangcj05** [comment]
@wanghy-anl The failures are caused by the library installation, it seems it may caused by the libraries that updated in dependency file:
```
Downloading contourpy-1.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.7/301.7 kB 80.6 MB/s eta 0:00:00
Using cached googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
Downloading tblib-2.0.0-py3-none-any.whl (11 kB)
Using cached wcwidth-0.2.8-py2.py3-none-any.whl (31 kB)
Downloading xyzservices-2023.10.0-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.2/57.2 kB 22.5 MB/s eta 0:00:00
Installing collected packages: wcwidth, sortedcontainers, py-spy, opencensus-context, nvidia-ml-py, libclang, flatbuffers, distlib, colorful, zict, xyzservices, typing-extensions, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, tblib, smart-open, rpds-py, pyyaml, pyasn1, pyarrow, protobuf, prometheus-client, opt-einsum, oauthlib, multidict, msgpack, MarkupSafe, markdown, lz4, locket, lark, keras, imageio, grpcio, google-pasta, gast, fsspec, frozenlist, filelock, elementpath, contourpy, click, cftime, cachetools, blessed, attrs, async-timeout, astunparse, absl-py, yarl, xmlschema, werkzeug, virtualenv, rsa, requests-oauthlib, referencing, pydantic, pyasn1-modules, partd, numdifftools, netcdf4, Jinja2, gpustat, googleapis-common-protos, aiosignal, python-sensors, jsonschema-specifications, google-auth, fmpy, dask, bokeh, aiohttp, jsonschema, google-auth-oauthlib, google-api-core, distributed, aiohttp-cors, tensorboard, ray, opencensus, tensorflow
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.8.0
    Uninstalling typing_extensions-4.8.0:
      Successfully uninstalled typing_extensions-4.8.0
ERROR: Exception:
Traceback (most recent call last):
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 452, in run
    installed = install_given_reqs(
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 807, in install
    install_wheel(
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
    _install_wheel(
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 692, in _install_wheel
    rows = get_csv_rows_for_installed(
  File "/home/civet/.conda/envs/raven_libraries/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 258, in get_csv_rows_for_installed
    old_record_path = cast("RecordPath", row[0])
IndexError: list index out of range

ERROR: exiting with code 2
```

**Comment by wanghy-anl** [comment]
@wangcj05 Congjian, could you share any insights to fix this issue? 
My commit is based on commit 28a735ac (merge of PR #2189) and I only changed the `dependencies.xml` within FARM submodule.
By the way, for the error message you posted above, may I know what OS does this info come from? I have a spare machine and I would like to build it with this OS to do further test.
Thanks, Haoyu

**Comment by wangcj05** [comment]
The failures happened for most of the machines, Linux, Mac and Windows. I will check other PRs to see if the failures are caused by other issues. I will keep you updated.

**Comment by wanghy-anl** [comment]
Thank you Congjian, much appreciated. 
Haoyu

**Comment by wangcj05** [comment]
Tests consistently failed at library installation stage. We have tested devel branch, and we do not see the issue. The difference that I see is the cvxopt library. @joshua-cogliati-inl Do you have any suggestion for this PR?

**Comment by joshua-cogliati-inl** [comment]
That looks more like a pip error than anything this pull request is doing, so at the moment I don't have a good idea.

**Comment by wanghy-anl** [comment]
Gents, I am testing this PR on my laptop with Ubuntu 18.04 LTS, and I can re-produce this error. Let me try to fix this issue.

**Comment by joshua-cogliati-inl** [comment]
It also repeatably occurs on devel with our pip install: https://civet.inl.gov/job/1811703/

"    old_record_path = cast("RecordPath", row[0])
IndexError: list index out of range"

So I suspect something changed in a package we are using, and now pip installs can fail.  This probably is triggering it by installing some more packages with pip from FARM. Thank you for looking into it.

**Comment by joshua-cogliati-inl** [comment]
If you manage to get them to pass locally, I would recommend that you push your changes.

**Comment by wanghy-anl** [comment]
@wangcj05 @joshua-cogliati-inl Gents, could you share the error info on Mingw Test? I tested it within Git Bash on my Windows 10 machine yesterday afternoon, and it passed all the tests...

**Comment by joshua-cogliati-inl** [comment]
The failure was in fetch, so I am rerunning the tests.

**Comment by wanghy-anl** [comment]
Thanks Joshua. How about the failed tests on qsubs sawtooth? Is there anything I can do to resolve it?
> The failure was in fetch (could not access hpcgitlab), so I am rerunning the tests.

**Comment by joshua-cogliati-inl** [comment]
> Thanks Joshua. How about the failed tests on qsubs sawtooth? Is there anything I can do to resolve it?
> 
> > The failure was in fetch (could not access hpcgitlab), so I am rerunning the tests.

The sawtooth computer is currently down for maintenance and upgrades, so for that one we have to wait a few weeks.  Sorry. (But they are highly likely to not be this pull requests' fault.)

**Comment by wanghy-anl** [comment]
> > Thanks Joshua. How about the failed tests on qsubs sawtooth? Is there anything I can do to resolve it?
> > > The failure was in fetch (could not access hpcgitlab), so I am rerunning the tests.
> 
> The sawtooth computer is currently down for maintenance and upgrades, so for that one we have to wait a few weeks. Sorry. (But they are highly likely to not be this pull requests' fault.)

Thanks for the info. 
I saw the Mingw tests are "Failed but allowed", is it a good time now to merge this PR and update the FARM submodule ID?

**Comment by wangcj05** [comment]
@wanghy-anl @joshua-cogliati-inl The changes just affect FARM plugin only. It is good for me to merge it. @joshua-cogliati-inl Please go ahead and merge this PR.

**Comment by wanghy-anl** [comment]
@joshua-cogliati-inl @wangcj05 Thanks Gents, much appreciated. Haoyu

**Pull request merged**
