### PR TITLE
Update FARM Submodule for EOY 2023

### PR DESCRIPTION
**Pull request by wanghy-anl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Continues [#1114](https://github.com/idaholab/raven/issues/1114)

##### What are the significant changes in functionality due to this change request?
Update FARM Submodule for EOY 2023

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wanghy-anl** [comment]
@dylanjm @wangcj05 Happy new year Gents. 
I would like to update the FARM submodule to reflect the changes we made at the end of 2023. 
This version of FARM works with the recently updated HERON (via #2235). 
Could you activate the automatic checks for this PR?
Thanks,
Haoyu

**Review by wangcj05 — APPROVED** [review]
changes are good.

**Comment by wangcj05** [comment]
@wanghy-anl Some tests in FARM and HERON  are failed on Windows machine.

**Comment by wanghy-anl** [comment]
> @wanghy-anl Some tests in FARM and HERON are failed on Windows machine.

Congjian, could you share the Windows test error message? Everything works on my Windows 10 machine...
BTW, I saw some tests failed on mac. Could you also share the associated error message?
Thanks.

**Comment by wangcj05** [comment]
@wanghy-anl Sorry for the late response, I was on travel. Please check the attache file for the plugin tests on Windows machine.  
[07_Test_Plugins.txt](https://github.com/idaholab/raven/files/13934618/07_Test_Plugins.txt)

**Comment by wangcj05** [comment]
@wanghy-anl For Mac machine test, the failures are not related to FARM.

**Comment by wanghy-anl** [comment]
> @wanghy-anl Sorry for the late response, I was on travel. Please check the attache file for the plugin tests on Windows machine. [07_Test_Plugins.txt](https://github.com/idaholab/raven/files/13934618/07_Test_Plugins.txt)

Congjian, Looking at its wall time, it seems to be an time out error. To further investigate, could you share the following file?
`\raven\plugins\FARM\tests\heron_validator\FARM_MIMO_selfLearning_fmuUpdate\Sweep_Runs_o\sweep\1\out~inner`
Thanks, Haoyu

**Comment by wangcj05** [comment]
> > @wanghy-anl Sorry for the late response, I was on travel. Please check the attache file for the plugin tests on Windows machine. [07_Test_Plugins.txt](https://github.com/idaholab/raven/files/13934618/07_Test_Plugins.txt)
> 
> Congjian, Looking at its wall time, it seems to be an time out error. To further investigate, could you share the following file? `\raven\plugins\FARM\tests\heron_validator\FARM_MIMO_selfLearning_fmuUpdate\Sweep_Runs_o\sweep\1\out~inner` Thanks, Haoyu

In this case, you may need to change the "max_time=1200" in your "tests" file, or you need to find a way to accelerate the test.

**Comment by wangcj05** [comment]
In addition, there are also two failed HERON tests, are these related to your changes?

**Comment by wanghy-anl** [comment]
> > > @wanghy-anl Sorry for the late response, I was on travel. Please check the attache file for the plugin tests on Windows machine. [07_Test_Plugins.txt](https://github.com/idaholab/raven/files/13934618/07_Test_Plugins.txt)
> > 
> > 
> > Congjian, Looking at its wall time, it seems to be an time out error. To further investigate, could you share the following file? `\raven\plugins\FARM\tests\heron_validator\FARM_MIMO_selfLearning_fmuUpdate\Sweep_Runs_o\sweep\1\out~inner` Thanks, Haoyu
> 
> In this case, you may need to change the "max_time=1200" in your "tests" file, or you need to find a way to accelerate the test.

I can change the max_time entry, but I am wondering why these tests took almost twice time to finish on the "Mingw" test machine. -- For instance, the `HERONvalidator_FARM_MIMO_selfLearning_noUpdate_WindowsOnly` took 468.82 secs on a single 2.7GHz core on my machine, but it took 881.16 secs on the "Mingw" test machine. 

I saw a line `/opt/build_root/raven/: ./run_tests -j 4 -l 4 --plugins` in the text file you sent. What does the argument "-l 4" stands for? I have never used this argument before.

**Comment by wanghy-anl** [comment]
> In addition, there are also two failed HERON tests, are these related to your changes?

I don't think so. All the HERON tests can pass on my windows machine. I am using the current submodule version of HERON, commit bec6cb76 on Dec 18.

**Comment by wanghy-anl** [comment]
@wangcj05 Congjian, Let me know if this new commit passed all the tests. Thanks. Haoyu

**Review by joshua-cogliati-inl — APPROVED** [review]
Updates to current FARM devel

**Comment by wanghy-anl** [comment]
@joshua-cogliati-inl Thank you Joshua for merging. Best, Haoyu

**Pull request merged**
