### PR TITLE
Farm submodule update

### PR DESCRIPTION
**Pull request by wanghy-anl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
This updates FARM submodule version to reflect the "ravenframework" change in April 2022 #1784
See also #1114 
##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wanghy-anl** [comment]
@wangcj05 Congjian, I saw 4 tests are not marked as "Passed":

- Test qsubs sawtooth — Failed
- Mingw Test — Failed but allowed
- Test Fedora 32 — Failed but allowed
- Test Ubuntu 18 PIP — Failed but allowed.

When I click on the "Details", it always pops up a message "You are not allowed to see results. Please sign in to an appropiate user."
Could you have a check on the details and let me know how to make them work?
Thanks,
Haoyu

**Comment by wangcj05** [comment]
Hi Haoyu,

I think you are good. The errors is not from FARM.

Best,

Congjian
________________________________
From: Haoyu Wang ***@***.***>
Sent: Friday, May 13, 2022 10:05 AM
To: idaholab/raven ***@***.***>
Cc: Congjian Wang ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] Farm submodule update (PR #1826)


@wangcj05<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwangcj05&data=05%7C01%7Ccongjian.wang%40inl.gov%7C3a1d6470fd6b437ef09c08da34fa6e89%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637880547438899134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=49HEwIdkjOibZ%2FsrzC99ChWjJxwWfPDpn9EtM4HJ6rY%3D&reserved=0> Congjian, I saw 4 tests are not marked as "Passed":

  *   Test qsubs sawtooth — Failed
  *   Mingw Test — Failed but allowed
  *   Test Fedora 32 — Failed but allowed
  *   Test Ubuntu 18 PIP — Failed but allowed.

When I click on the "Details", it always pops up a message "You are not allowed to see results. Please sign in to an appropiate user."
Could you have a check on the details and let me know how to make them work?
Thanks,
Haoyu

**Comment by wangcj05** [comment]
SAWTOOTH tests failed due to the conflict of new Conda and gcc library on SAWTOOTH. See issue #1828 and fix PR #1827

**Comment by wangcj05** [comment]
This PR is good, there is no source code update for RAVEN, only submodule ID update. The failure of SAWTOOTH tests is not due to this PR (see previous comment). PR can be merged.

**Review by wangcj05 — APPROVED** [review]

**Comment by wanghy-anl** [comment]
Thank you Congjian, much appreciated!
Haoyu

**Pull request merged**
