### PR TITLE
updated to latest TEAL devel

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
See #1258

##### What are the significant changes in functionality due to this change request?
Updates TEAL since ... a long time.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [ ] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wangcj05** [comment]
both LOGOS and HERON are failed due to the update of TEAL. Does this affect the HERON workshop @PaulTalbot-INL? If so,  we can postpone the merge of this PR. In addition, I also need to figure out the failure of LOGOS due to TEAL updates.

**Comment by PaulTalbot-INL** [comment]
This changes the behavior of the interest handling in TEAL to work as expected, which does yield a diff in two tests in HERON (since the underlying assumptions about interest handling changed). It doesn't cause failures in HERON, but would be nice to postpone until we can update HERON to reflect this new TEAL version.

I think the original behavior can be obtained by modifying the "interest" tag for specific cashflows; I think the associated TEAL PR has more details on those changes.

**Comment by wangcj05** [comment]
@PaulTalbot-INL FYI, I have merged Josh's PR #1784, which I think it will break TEAL. Could you update TEAL with the current devel of RAVEN first, and then update the TEAL submodule ID for this PR? Sorry for the inconvenience.

**Review by wangcj05 — CHANGES_REQUESTED** [review]
See my comment.

**Comment by PaulTalbot-INL** [comment]
You can see this is over a month old; I made this PR as a demonstration for how to update the TEAL submodule in RAVEN, but never expected it would go this long without merging.

I will suggest that you pass on maintenance requests to @worseliz as the TEAL owner.

**Comment by PaulTalbot-INL** [comment]
Closing as this update to TEAL was broken by RAVEN PR #1784.

**Pull request closed without merging**
