### PR TITLE
Parallel improvements

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address?
#1809

##### What are the significant changes in functionality due to this change request?
Various changes to improve the parallel and debugging the parallel.
1. Prior to this, using RavenRunsRaven always switches on MPI mode.  This causes them to run with mpiexec, when they might want to be run with ray.
2. This now waits for ray servers to finish starting.  Before, RAVEN ignored them and they became zombies.
3. This adds various debugging information that is useful for diagnosing parallel problems.
4. The RavenRunRaven code is switched to internal parallel on the inner to test inner raven runs raven with internalParallel. It also increases it to 8 x 8 so that it will always run on more than one node.
5. Requests that ray find an available port, instead of always using 6379.
6. Don't start ray if we are just doing a remote run (as in don't start ray, then do a qsub, then shutdown ray, then in the qsub'd raven start ray again)

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
An email something like this should be sent out if this is approved:
With the following pull request
https://github.com/idaholab/raven/pull/1825
for Raven Runs Raven workflows, the inner runs no-longer have <mode>mpi</mode> automatically added.  If you wish to 
do this, you will need to manually add that to your inner input.

**Comment by dylanjm** [comment]
@joshua-cogliati-inl

> you will need to manually add that to your inner input.

It would be nice to additionally specify how to do this

**Review by PaulTalbot-INL — DISMISSED** [review]
Code changes look good to me.

**Comment by PaulTalbot-INL** [comment]
Some odd failures showing up on the Sawtooth tests, one unit test and one optimization test

**Comment by joshua-cogliati-inl** [comment]
> @joshua-cogliati-inl
> 
> > you will need to manually add that to your inner input.
> 
> It would be nice to additionally specify how to do this

Git hub ate my example: `<mode>mpi</mode>`

**Comment by joshua-cogliati-inl** [comment]
> Some odd failures showing up on the Sawtooth tests, one unit test and one optimization test

Yes, I am trying to figure out if those are related to this change, or something else.

**Comment by joshua-cogliati-inl** [comment]
Hm, this does seem to have increased the reliability of ./test_qsubs.sh
Ran 2 until failed with: "failed: tests/cluster_tests/AdaptiveSobol/test_parallel_adaptive_sobol"
Ran 10 until failed with: "tests/cluster_tests/AdaptiveSobol/test_parallel_adaptive_sobol"
Ran 3 until failed with: "tests/cluster_tests/InternalParallel/test_parallel_hybride_model_external"
Ran 10 and still running.
No Raven Runs Raven Code failures yet.

**Review by wangcj05 — APPROVED** [review]
Changes are good.

**Comment by wangcj05** [comment]
PR has been approved, and all tests are green. Checklist is satisfied.

**Pull request merged**
