### PR TITLE
FARM Submodule Update, with new ARMA and gold files

### PR DESCRIPTION
**Pull request by wanghy-anl**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
#1114 
Updated ARMA rom and gold files following recent change in raven

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by wanghy-anl** [comment]
@wangcj05 Hey Congjian, I am here to update FARM submodule again. @PaulTalbot-INL  mentioned today that the ARMA structure changed a little bit and suggest me to have a check, so I updated the FARM static ARMA rom files and the gold files. Still, you may see one test fails in FARM/tests/heron_validator/FARM_Delta_FMU/, and this test would pass after the HERON submodule ID get updated. 
Thanks, Haoyu

**Comment by dgarrett622** [comment]
@wanghy-anl I'm reviewing the HERON submodule update. Once the tests pass on that one, I'll start the tests on the FARM submodule update and get it merged in once tests pass.

**Review by dgarrett622 — APPROVED** [review]

**Comment by wanghy-anl** [comment]
> @wanghy-anl I'm reviewing the HERON submodule update. Once the tests pass on that one, I'll start the tests on the FARM submodule update and get it merged in once tests pass.

@dgarrett622 Daniel, all the FARM tests will fail if you run the HERON submodule update tests first. Let me explain. 
When running the test for HERON submodule update, the following combination will be used:
- HERON at devel version d420aeb6;
- FARM at submodule version 68510c48.
The current submodule version of FARM contains obsolete static ARMA roms, which will not run properly under the current raven version. All the FARM related tests will fail.

I will suggest to run the tests on this PR #1927 first, then merge to update FARM submodule, and finally run HERON submodule update tests. The first step of this procedure will use the combination of:
- HERON at submodule version 9b02f089;
- FARM at devel version ce820003.
You will see the majority of tests passed but only one fails on windows machine. The FARM at ce820003 commit contains the updated ARMA rom, but the HERON at submodule version doesn't contain the "FARM_Delta_FMU" entry on the HERON/src/validators/factory.py. 

When you run the HERON submodule update tests after you merged this PR #1927 , you will see this FARM_Delta_FMU test passed, because the new HERON submodule version contains this "FARM_Delta_FMU" entry, from my PR https://github.com/idaholab/HERON/pull/192

Let me know how it sounds!
Haoyu

**Comment by PaulTalbot-INL** [comment]
The RAVEN ARMA changes are in regardless of what submod of HERON you're using, right? Updating the HERON submodule does not require all the FARM submod tests to pass, so I'm not sure why we would put off the HERON submodule tests.

https://github.com/idaholab/raven/pull/1928 indicates the HERON tests for the HERON submodule update are passing fine, but FARM tests are failing, which is to be expected since you're still updating your submodule as well. When both are updated, then FARM tests relying on HERON should pass, right?

**Comment by dgarrett622** [comment]
Looks like FARM tests pass, this is ready to merge.

**Comment by wanghy-anl** [comment]
> Looks like FARM tests pass, this is ready to merge.

Thanks Daniel!

**Pull request merged**
