### PR TITLE
Input improvements

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address?
Refs #84 

##### What are the significant changes in functionality due to this change request?
This switches more of RAVEN to the InputData input handler.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
I still am working on it, but I will shortly run out of time.

**Comment by joshua-cogliati-inl** [comment]
I did not finish converting the Sampler directory.  Note that now everything is parsed with InputData in the sampler directory, but most of the input handling is still done directly on the XML. Some of the tricks used are going to require a bit of thought to do in the Sampler, like where an xml string is generated, or where a xml node is modified and then passed to a different place.


When this is approved, it will need an email something like this:

This merge brings two changes that might affect you.

1. The input checking has gotten stricter.  This should help when debugging inputs, but also, there are inputs that would have passed the previous checker but now will error out.  Usually this is because the input was incorrect (possibly it just had things that were ignored previously.)

It is possible that there are valid inputs that now no longer run.  If you find any inputs that should run but fail, let the mailing list know and we can check and fix RAVEN if needed.

2. In the BasicStatistics, the way to specify the percent used with the percentile has changed.   Now, there is a parameter percent that is used.

So:
<percentile_0.1>x,y</percentile_0.1>
is now:
<percentile percent="0.1">x,y</percentile>

There is a conversion script scripts/conversionScripts/toPercentileParameter.py available to convert old input files to the new format.

**Comment by alfoa** [comment]
Josh,
can you add the comments above (the missing modules/Classes) etc in multiple Issues?
And can you prepare an email for the modification in the "percentile" ?
Thanks

**Comment by joshua-cogliati-inl** [comment]
I am not quite sure what you want commented.  There is an email in: https://github.com/idaholab/raven/pull/395#issuecomment-334865681 but I can expand it if needed.

**Comment by alfoa** [comment]
I would like just that you open an issue with all the modules/classes that miss the implementation of the iNput checker... Just to keep track of what is missing to do.

**Comment by joshua-cogliati-inl** [comment]
I detailed what is still needed on the issue for this: https://github.com/idaholab/raven/issues/84#issuecomment-346063460

**Comment by alfoa** [comment]
----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code. ***OK***
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts). ***n/a***
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details. ***OK***
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass. ***OK***
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True. ***n/a***
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync. ***n/a***
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done. ***#84. Not closed since the work is not completed yet***
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added? ***n/a***

**Comment by alfoa** [comment]
Check list passed...

Once the tests are green, it can be merged...

Thank you.

**Comment by alfoa** [comment]
For unknown reasons, the Windows machine is hanging (waiting for something (but no other jobs are running))

**Comment by alfoa** [comment]
@bobkinl @joshua-cogliati-inl

**Comment by alfoa** [comment]
I merge this even if the Windows tests did not start. The error was about the input checker and the modification has been fully tested by the other regression machines...

**Comment by bobkinl** [comment]
The Windows machine (RAVENHOME) is in a funny state...I can't get in.  It probably needs a reboot.  I have submitted an issue to the OpsCenter.

**Pull request merged**
