### PR TITLE
RrR Return Database

### LINKED ISSUE #1464: [TASK] Return Databases from RrR Inner
--------
Issue Description
--------

As an alternative to CSVs, we could more quickly read NetCDF Databases as returns from RAVEN CodeInterface runs.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #1464
Needed before we can address https://github.com/idaholab/HERON/issues/12

##### What are the significant changes in functionality due to this change request?
Allows RAVEN interface to permit RAVEN inner to return ND data to RAVEN outer via a database (as an alternative to a CSV from an OutStream)

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

**Comment by alfoa** [comment]
@PaulTalbot-INL the other 2 PR has been merged. When you rebase this I can start reviewing it

**Review by alfoa — APPROVED** [review]

**Comment by alfoa** [comment]
No code changes requested. Once all the tests pass, this can be merged..

**Comment by PaulTalbot-INL** [comment]
Two qsub tests failed, unrelated to this PR:
```
Failed tests/framework/PostProcessors/InterfacedPostProcessor/interfacedPostProcessorParallel
Failed tests/framework/PostProcessors/InterfacedPostProcessor/interfacedPostProcessor
```
with the trace such as:
```
2021-03-09 11:24:04,687	INFO services.py:1092 -- View the Ray dashboard at http://127.0.0.1:8265
F0309 11:24:14.737923 16662 16662 raylet_client.cc:57] Could not connect to socket /tmp/ray/session_2021-03-09_11-24-01_086033_16662/sockets/raylet
*** Check failure stack trace: ***
    @     0x7fce828c587d  google::LogMessage::Fail()
    @     0x7fce828c6cec  google::LogMessage::SendToLog()
    @     0x7fce828c5559  google::LogMessage::Flush()
    @     0x7fce828c5771  google::LogMessage::~LogMessage()
    @     0x7fce82878be9  ray::RayLog::~RayLog()
    @     0x7fce8259402f  ray::raylet::RayletConnection::RayletConnection()
    @     0x7fce82595340  ray::raylet::RayletClient::RayletClient()
    @     0x7fce8253889b  ray::CoreWorker::CoreWorker()
    @     0x7fce8253c454  ray::CoreWorkerProcess::CreateWorker()
    @     0x7fce8253d6c2  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x7fce8253e09b  ray::CoreWorkerProcess::Initialize()
    @     0x7fce8246e006  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
    @     0x7fce8246f7b5  __pyx_tp_new_3ray_7_raylet_CoreWorker()
    @     0x562734ac08d9  _PyObject_FastCallKeywords
    @     0x562734b2627e  _PyEval_EvalFrameDefault
    @     0x562734a69640  _PyEval_EvalCodeWithName
    @     0x562734ab90b7  _PyFunction_FastCallKeywords
    @     0x562734b22539  _PyEval_EvalFrameDefault
    @     0x562734a69640  _PyEval_EvalCodeWithName
    @     0x562734ab90b7  _PyFunction_FastCallKeywords
    @     0x562734b22539  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b21466  _PyEval_EvalFrameDefault
    @     0x562734a68d09  _PyEval_EvalCodeWithName
    @     0x562734a69be4  PyEval_EvalCodeEx
    @     0x562734a69c0c  PyEval_EvalCode*** Check failure stack trace: ***
    @     0x7fce828c587d  google::LogMessage::Fail()
    @     0x7fce828c6cec  google::LogMessage::SendToLog()
    @     0x7fce828c5559  google::LogMessage::Flush()
    @     0x7fce828c5771  google::LogMessage::~LogMessage()
    @     0x7fce82878be9  ray::RayLog::~RayLog()
    @     0x7fce8259402f  ray::raylet::RayletConnection::RayletConnection()
    @     0x7fce82595340  ray::raylet::RayletClient::RayletClient()
    @     0x7fce8253889b  ray::CoreWorker::CoreWorker()
    @     0x7fce8253c454  ray::CoreWorkerProcess::CreateWorker()
    @     0x7fce8253d6c2  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x7fce8253e09b  ray::CoreWorkerProcess::Initialize()
    @     0x7fce8246e006  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
    @     0x7fce8246f7b5  __pyx_tp_new_3ray_7_raylet_CoreWorker()
    @     0x562734ac08d9  _PyObject_FastCallKeywords
    @     0x562734b2627e  _PyEval_EvalFrameDefault
    @     0x562734a69640  _PyEval_EvalCodeWithName
    @     0x562734ab90b7  _PyFunction_FastCallKeywords
    @     0x562734b22539  _PyEval_EvalFrameDefault
    @     0x562734a69640  _PyEval_EvalCodeWithName
    @     0x562734ab90b7  _PyFunction_FastCallKeywords
    @     0x562734b22539  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b216f0  _PyEval_EvalFrameDefault
    @     0x562734ab8e2b  _PyFunction_FastCallKeywords
    @     0x562734b21466  _PyEval_EvalFrameDefault
    @     0x562734a68d09  _PyEval_EvalCodeWithName
    @     0x562734a69be4  PyEval_EvalCodeEx
    @     0x562734a69c0c  PyEval_EvalCode
```
Invalidating.

**Comment by alfoa** [comment]
Checklist passed...

Merging...

**Pull request merged**
