### PR TITLE
Generalized typechecking

### PR DESCRIPTION
**Pull request by PaulTalbot-INL**
Move typechecking from `isinstance` checks in the code to (hopefully) efficient and thorough checks in `mathUtils`.

It went in mathUtils because we need numpy, which we should not need in utils if I recall the design correctly.

Converts the data objects to use the same.

### CODE REVIEW

**Comment by wangcj05** [comment]
@PaulTalbot-INL you need to resolve the conflicts. @alfoa Could you take a look at this PR?

**Comment by PaulTalbot-INL** [comment]
Done.

**Comment by wangcj05** [comment]
```
**** SUMMARY ****
*********************************
Number of success first file:
429
Number of success second file:
429
 .
*********************************
```

**Comment by wangcj05** [comment]
Good to go

**Pull request merged**
