### PR TITLE
Adding `<interactive />` tag specification to the ToplogicalDecomposition PP

### LINKED ISSUE #359: Code Coverage drop
The code coverage has dropped due to a failure on the input check of one of the UI tests:

https://hpcsc.inl.gov/ssl/RAVEN/python-coverage/

This can be corrected by either adding the `interactive` node to the specification or removing the need for it in the file. This feature is a bit buried in details as it requires both the a command line flag and a input file specification. This is somewhat by design in order to force the user to explicitly request the feature in case they expect an automated pipeline of events to occur, and for this reason I am leaning towards the prior solution of adding the flag to the input specification.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? *improvement made*
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) *Tested as part of code coverage*
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? *No email needed*
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? *No stable*
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? *Closed with merge request*

Issue Close reviewed by @joshua-cogliati-inl on 2017-Sept-18

### PR DESCRIPTION
**Pull request by maljovec**
Closes #359.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code. *Done*
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).  *No real change, but this does fix missing documentation*
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details. *Yes*
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass. *Yes*
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.  *No significant functionality added*
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync. *No change*
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.  *Done*
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?  *No change*

Checklist review by @joshua-cogliati-inl on 2017-Sept-18

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
Can you explain how this fixes the coverage?  (As in how does changing the input specification cause this to work?)  Thanks.

**Comment by maljovec** [comment]
Sure thing. So, when I investigated the coverage tests on the VM that replicates the coverage test machine, I saw the following error:

```
IOError: Child interactive not in allowed sub elements in PostProcessor
```

The reason this was showing up is because we added the input specification for the Post-Processors, however this feature was not documented in the user manual (which I need to fix now). So, what ends up happening is the test fails before starting because the input is "invalid" given the current specification.

**Comment by joshua-cogliati-inl** [comment]
Okay, thanks for the explanation.  Are you going to update the documentation in this merge?  Thanks.

**Comment by maljovec** [comment]
Yes, the documentation should be added now. I am also adding the coverage tests to CIVET to ensure that this does indeed fix the problem.

**Pull request merged**
